env:
  global:
    - SITL_SPEEDUP=10
    - SITL_RATE=200

python:
  - "2.7"

install:
  - 'sudo pip install . -UI'
  - 'sudo pip install -r requirements.txt -UI'

script:
#  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || nosetests -svx dronekit.test.web'
  - 'nosetests -svx dronekit.test.unit'
  - 'nosetests -svx dronekit.test.sitl'

git:
  depth: 10

language: objective-c

notifications:
  email: false
  slack:
    secure: IYgZ83X065I/LljGrPEACZms+KDwrojiQbboFHhvNxL2Zkc5jHqwBK6PD1BsJh2JVun9fCZ1v2R8KuDsf+Qz2dCximdOZcHI81L9JUOZYuSJ2TVlbKiC00WdXpcQ6g7pDTLm/mGBoPxC+MuC5l8zZdbpPBpEa0F/YCe/n7tbT+g=

matrix:
  fast_finish: true

branches:
  only:
    - master
    - patch
    - major
    - minor
